# Generated by Django 4.2.1 on 2023-07-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_food_options_food_created_food_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
